services:
  backendtesting:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/home/app/.aspnet/https/aspnetcore-localhost-40D62B250BC0795076D79A3EFA598BA83CBAF4DE.pfx
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ~/.aspnet/dev-certs/https:/home/app/.aspnet/https:ro
